### ISSUE TITLE
error in when running bandup in example2 step 4

### ISSUE THREAD

**Issue by LoutfiLoutfi** [band-unfolding/bandup#17]
Hello;
i compiled the last version of bandup. i m using python 2.7 and as default and QE 6.4. when following the tutorial example 2 ( bulk Si) and in the step 4 i have an error:

    You have compiled BandUP without support for QE!
    and
    unfolded_EBS_symmetry-averaged.dat does not exist or is not accessible.

i tried to solve the problem without success.
any suggestion!!!?

**Comment by stepan-tsirkin** [comment]
Dear @LoutfiLoutfi,
 
It is true that there are problems with the new versions of QE, since 6.4, I think. 
Could you try the new pythonic verison of BandUP <https://github.com/band-unfolding/banduppy> . 
Please install it with `pip3 install banduppy` and try an example from the repository. In case of problems, please open an issue in that repository. 

Regards,
Stepan.

**Comment by NickRybin** [comment]
I have tested QE 6.1,  6.2 ... 6.6 and in all cases there were problems running unfolding wiht bandup. Then I have tried banduppy and it works well. @LoutfiLoutfi you can clone banduppy repository from git and then move to the tutorial folder. The example there deals exactly with QE. If you already have done all the calculations then the unfolding would be straightforward. 

Cheers,
Nikita
